name: Publish Website

on:
  workflow_dispatch:
  push:
    branches:
     - main

jobs:
  publish:
    name: Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      max-parallel: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Project
        run: quarto render --output-dir _site
        shell: bash

      - name: Publish Project
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
